### ISSUE TITLE
Cannot run tests locally

### ISSUE THREAD

**Issue by aless10** [Tsadoq/kompy#2]
Hi, I forked the repo and run the tests but it seems that you need some env variables set:

- KOMOOT_EMAIL
- KOMOOT_PASSWORD

Maybe you can add this detail to the readme or try to remove this dependency from the tests so that you don't need to have a valid account to run the tests (even in the github actions).

**Comment by Tsadoq** [comment]
Hi @aless10 , I'll add this to the documentation. Unfortunately you need to set you (account) email and password to run the tests. In the future I plan on mocking the connection for the tests.
